// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlzugdviplpnqdznknxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsenVnZHZpcGxwbnFkem5rbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzE4ODgsImV4cCI6MjA2MDYwNzg4OH0.OY1rRmuCT3goxRKxP9sARxVlEwkqLdpwFFKjs1upzxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);